In [1]:
pip install selenium

Requirement already satisfied: selenium in c:\users\luigi\anaconda3\lib\site-packages (4.1.5)
Requirement already satisfied: trio~=0.17 in c:\users\luigi\anaconda3\lib\site-packages (from selenium) (0.20.0)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\luigi\anaconda3\lib\site-packages (from selenium) (1.26.7)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\luigi\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: attrs>=19.2.0 in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: sniffio in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.6)
Requirement already satisfied: async-generator>=1.9 in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: outcome in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: idna in c:\users\luigi\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.2)
Requirement already satisfied: pycparser in c:\users\luigi\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\luigi\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\luigi\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\luigi\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\luigi\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.8)
Requirement already satisfied: certifi in c:\users\luigi\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: six>=1.5.2 in c:\users\luigi\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\luigi\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install splinter

Requirement already satisfied: splinter in c:\users\luigi\anaconda3\lib\site-packages (0.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install webdriver_manager

Requirement already satisfied: webdriver_manager in c:\users\luigi\anaconda3\lib\site-packages (3.5.4)
Requirement already satisfied: requests in c:\users\luigi\anaconda3\lib\site-packages (from webdriver_manager) (2.26.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\luigi\anaconda3\lib\site-packages (from requests->webdriver_manager) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\luigi\anaconda3\lib\site-packages (from requests->webdriver_manager) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\luigi\anaconda3\lib\site-packages (from requests->webdriver_manager) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\luigi\anaconda3\lib\site-packages (from requests->webdriver_manager) (2.0.4)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from bs4 import BeautifulSoup as bs
import pandas as pd
from splinter import Browser
import requests
from webdriver_manager.chrome import ChromeDriverManager

In [5]:
# Setup splinter
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

====== WebDriver manager ======
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\luigi\.wdm\drivers\chromedriver\win32\101.0.4951.41]

## NASA MARS NEWS

In [6]:
# URL of page to be scraped
url = 'https://redplanetscience.com/'
browser.visit(url)

#Set an HTML object
html = browser.html

# Parse HTML with Beautiful Soup
soup = bs(html, 'html.parser')

In [7]:
# Retrieve the latest element that contains news title and news_paragraph
news_title = soup.find_all('div', class_='content_title')[0].text
news_p = soup.find_all('div', class_='article_teaser_body')[0].text

In [8]:
print(news_title)
print(news_p)

Follow NASA's Perseverance Rover in Real Time on Its Way to Mars
A crisply rendered web application can show you where the agency's Mars 2020 mission is right now as it makes its way to the Red Planet for a Feb. 18, 2021, landing.

## JPL Mars Space Images - Featured Image

In [9]:
space_url = 'https://spaceimages-mars.com/'
browser.visit(space_url)
browser.links.find_by_partial_text('FULL IMAGE').click()
#Set an HTML object
html_space = browser.html

# Parse HTML with Beautiful Soup
soup2 = bs(html_space, 'html.parser')

In [10]:
image_url = soup2.find('img',attrs={'class':'fancybox-image'})['src']

In [11]:
#Website URL
web_main_url = 'https://spaceimages-mars.com/'

In [12]:
featured_image_url = web_main_url + image_url

In [13]:
print(featured_image_url)

https://spaceimages-mars.com/image/featured/mars2.jpg

## Mars Facts

In [14]:
url_facts = 'https://galaxyfacts-mars.com/'

In [15]:
tables = pd.read_html(url_facts)
mars_fact_df = tables[0]
mars_fact_df

                         0                1                2
0  Mars - Earth Comparison             Mars            Earth
1                Diameter:         6,779 km        12,742 km
2                    Mass:  6.39 × 10^23 kg  5.97 × 10^24 kg
3                   Moons:                2                1
4       Distance from Sun:   227,943,824 km   149,598,262 km
5          Length of Year:   687 Earth days      365.24 days
6             Temperature:     -87 to -5 °C      -88 to 58°C

In [16]:
mars_fact_df.columns = ['parameters','plannet mars', 'plannet earth']
mars_fact_df

                parameters     plannet mars    plannet earth
0  Mars - Earth Comparison             Mars            Earth
1                Diameter:         6,779 km        12,742 km
2                    Mass:  6.39 × 10^23 kg  5.97 × 10^24 kg
3                   Moons:                2                1
4       Distance from Sun:   227,943,824 km   149,598,262 km
5          Length of Year:   687 Earth days      365.24 days
6             Temperature:     -87 to -5 °C      -88 to 58°C

In [17]:
mars_fact_df.set_index('parameters', inplace=True)
mars_fact_df

                            plannet mars    plannet earth
parameters
Mars - Earth Comparison             Mars            Earth
Diameter:                       6,779 km        12,742 km
Mass:                    6.39 × 10^23 kg  5.97 × 10^24 kg
Moons:                                 2                1
Distance from Sun:        227,943,824 km   149,598,262 km
Length of Year:           687 Earth days      365.24 days
Temperature:                -87 to -5 °C      -88 to 58°C

In [18]:
tables = pd.read_html(url_facts)
mars_fact_df2 = tables[1]
mars_fact_df2

                      0                              1
0  Equatorial Diameter:                       6,792 km
1       Polar Diameter:                       6,752 km
2                 Mass:  6.39 × 10^23 kg (0.11 Earths)
3                Moons:          2 ( Phobos & Deimos )
4       Orbit Distance:       227,943,824 km (1.38 AU)
5         Orbit Period:           687 days (1.9 years)
6  Surface Temperature:                   -87 to -5 °C
7         First Record:              2nd millennium BC
8          Recorded By:           Egyptian astronomers

In [19]:
mars_fact_df2.columns = ['parameters','result']
mars_fact_df2

             parameters                         result
0  Equatorial Diameter:                       6,792 km
1       Polar Diameter:                       6,752 km
2                 Mass:  6.39 × 10^23 kg (0.11 Earths)
3                Moons:          2 ( Phobos & Deimos )
4       Orbit Distance:       227,943,824 km (1.38 AU)
5         Orbit Period:           687 days (1.9 years)
6  Surface Temperature:                   -87 to -5 °C
7         First Record:              2nd millennium BC
8          Recorded By:           Egyptian astronomers

In [20]:
mars_fact_df2.set_index('parameters', inplace=True)
mars_fact_df2

                                             result
parameters
Equatorial Diameter:                       6,792 km
Polar Diameter:                            6,752 km
Mass:                 6.39 × 10^23 kg (0.11 Earths)
Moons:                        2 ( Phobos & Deimos )
Orbit Distance:            227,943,824 km (1.38 AU)
Orbit Period:                  687 days (1.9 years)
Surface Temperature:                   -87 to -5 °C
First Record:                     2nd millennium BC
Recorded By:                   Egyptian astronomers

In [21]:
#mars_fact_df.to_html()
with open('mars_facts_df.html', 'w') as fo:
    mars_fact_df.to_html(fo)

In [22]:
#mars_fact_df.to_html()
with open('mars_facts_df2.html', 'w') as fo:
    mars_fact_df2.to_html(fo)

## Mars Hemispheres

In [23]:
url_hemi = 'https://marshemispheres.com/'
browser.visit(url_hemi)

# Set an HTML object
html_hemi = browser.html

# Parse HTML with Beautiful Soup
soup_hemi = bs(html_hemi, 'html.parser')
print(soup_hemi.prettify())

<html lang="en">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <link href="css/jquery-ui.css" rel="stylesheet" type="text/css"/>
  <title>
   Astropedia Search Results | GUSS Astrogeology Science Center
  </title>
  <meta content="GUSS Astrogeology Science Center Astropedia search results." name="description"/>
  <meta content="GUSS,Astrogeology Science Center,Cartography,Geology,Space,Geological Survey,Mapping" name="keywords"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport"/>
  <link href="css/main.css" media="screen" rel="stylesheet"/>
  <link href="css/print.css" media="print" rel="stylesheet"/>
  <link href="#" rel="icon" type="image/x-ico"/>
 </head>
 <body id="results">
  <header>
   <a href="#" style="float:right;margin-top:10px;" target="_blank">
    <img alt="USGS: Science for a Changing World" class="logo" height="60" src="images/usgs_logo_main_2x.png"/>
   </a>
   <a href="#" style="float:right;margin-top:5px;margin-right:20px;" target="_blank">
    <img alt="NASA" class="logo" height="65" src="images/nasa-logo-web-med.png"/>
   </a>
  </header>
  <div class="wrapper">
   <div class="container">
    <div class="widget block bar">
     <a href="https://astrogeology.usgs.gov/search" style="float:right;text-decoration:none;">
      <img alt="Astropedia" src="images/astropedia-logo-main.png" style="width:200px;border:none;float:right;"/>
      <div style="clear:both;font-size:.8em;float:right;color:#888;">
       Lunar and Planetary Cartographic Catalog
      </div>
     </a>
     <div style="float:left;height:60px;">
     </div>
    </div>
    <div class="full-content">
     <section class="block" id="results-accordian">
      <div class="result-list" data-section="product" id="product-section">
       <div class="accordian">
        <h2>
         Products
        </h2>
        <span class="count">
         4 Results
        </span>
        <span class="collapse">
         Collapse
        </span>
       </div>
       <div class="collapsible results">
        <div class="item">
         <a class="itemLink product-item" href="cerberus.html">
          <img alt="Cerberus Hemisphere Enhanced thumbnail" class="thumb" src="images/39d3266553462198bd2fbc4d18fbed17_cerberus_enhanced.tif_thumb.png"/>
         </a>
         <div class="description">
          <a class="itemLink product-item" href="cerberus.html">
           <h3>
            Cerberus Hemisphere Enhanced
           </h3>
          </a>
          <span class="subtitle" style="float:left">
           image/tiff 21 MB
          </span>
          <span class="pubDate" style="float:right">
          </span>
          <br/>
          <p>
           Mosaic of the Cerberus hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. This mosaic is composed of 104 Viking Orbiter images acquired…
          </p>
         </div>
         <!-- end description -->
        </div>
        <div class="item">
         <a class="itemLink product-item" href="schiaparelli.html">
          <img alt="Schiaparelli Hemisphere Enhanced thumbnail" class="thumb" src="images/08eac6e22c07fb1fe72223a79252de20_schiaparelli_enhanced.tif_thumb.png"/>
         </a>
         <div class="description">
          <a class="itemLink product-item" href="schiaparelli.html">
           <h3>
            Schiaparelli Hemisphere Enhanced
           </h3>
          </a>
          <span class="subtitle" style="float:left">
           image/tiff 35 MB
          </span>
          <span class="pubDate" style="float:right">
          </span>
          <br/>
          <p>
           Mosaic of the Schiaparelli hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. The images were acquired in 1980 during early northern…
          </p>
         </div>
         <!-- end description -->
        </div>
        <div class="item">
         <a class="itemLink product-item" href="syrtis.html">
          <img alt="Syrtis Major Hemisphere Enhanced thumbnail" class="thumb" src="images/55a0a1e2796313fdeafb17c35925e8ac_syrtis_major_enhanced.tif_thumb.png"/>
         </a>
         <div class="description">
          <a class="itemLink product-item" href="syrtis.html">
           <h3>
            Syrtis Major Hemisphere Enhanced
           </h3>
          </a>
          <span class="subtitle" style="float:left">
           image/tiff 25 MB
          </span>
          <span class="pubDate" style="float:right">
          </span>
          <br/>
          <p>
           Mosaic of the Syrtis Major hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. This mosaic is composed of about 100 red and violet…
          </p>
         </div>
         <!-- end description -->
        </div>
        <div class="item">
         <a class="itemLink product-item" href="valles.html">
          <img alt="Valles Marineris Hemisphere Enhanced thumbnail" class="thumb" src="images/4e59980c1c57f89c680c0e1ccabbeff1_valles_marineris_enhanced.tif_thumb.png"/>
         </a>
         <div class="description">
          <a class="itemLink product-item" href="valles.html">
           <h3>
            Valles Marineris Hemisphere Enhanced
           </h3>
          </a>
          <span class="subtitle" style="float:left">
           image/tiff 27 MB
          </span>
          <span class="pubDate" style="float:right">
          </span>
          <br/>
          <p>
           Mosaic of the Valles Marineris hemisphere of Mars projected into point perspective, a view similar to that which one would see from a spacecraft. The distance is 2500 kilometers from the surface of…
          </p>
         </div>
         <!-- end description -->
        </div>
       </div>
       <!-- end this-section -->
      </div>
     </section>
    </div>
    <div class="navigation clear" style="display: none;">
     <a class="itemLink product-item" href="#" onclick="showMain()">
      <h3>
       Back
      </h3>
     </a>
    </div>
   </div>
   <footer>
    <div class="left">
     <a href="#">
      Search
     </a>
     |
     <a href="#">
      About
     </a>
     |
     <a href="#">
      Contact
     </a>
    </div>
    <div class="right">
     <a href="#">
      GUSS Science Center
     </a>
    </div>
   </footer>
  </div>
  <div class="page-background" style="
         background:url('./images/mars.jpg');
         filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(
         src='./images/mars.jpg', sizingMethod='scale');
         ">
  </div>
  <script type="text/javascript">
   var baseUrl = "";
  </script>
  <script src="js/jquery.min.js" type="text/javascript">
  </script>
  <script src="js/jquery-ui.min.js" type="text/javascript">
  </script>
  <script src="js/general.js" type="text/javascript">
  </script>
 </body>
</html>

In [24]:
# Retrieve items that contain mars hemi info
item = soup_hemi.find_all('div', class_='item')

# Create an empty list to hold it
hemi_list = []

# Main url
hemi_main_url = 'https://marshemispheres.com/'

In [25]:
# Create for loop 
for i in item:
    
    title = i.find('h3').text
    
    partial_img = i.find('a', class_='itemLink product-item')['href']
    
    browser.visit(hemi_main_url + partial_img)
    
    partial_html = browser.html
    
    soup_par = bs(partial_html, 'html.parser')
    
    image_url = hemi_main_url + soup_par.find('img', class_='wide-image')['src']
    
    hemi_list.append({"title": title, "img_url": image_url})

In [ ]:
hemi_list